apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-ipo-api
spec:
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  # ---------
  # Backend
  #---------- 

  - name: backend
    image: procosys.azurecr.io/ipo/api:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: 98cb737b-5c00-4ae6-962b-29c562b7ea21 # Managed identity: pcs-ipo-dev-mi
      imageTagName: latest
      variables:
        API__Audience: api://2e1868db-3024-45a9-b3f1-568e85586244
        Application__AppConfigurationUrl: https://pcs-ipo-non-prod-config.azconfig.io
        Application__LibraryApiScope: api://fdf5086c-009f-4407-b7bb-d2ece26dea45/ReadWrite
        Application__ObjectId: d675f4cf-4c71-4e33-aa61-900404864819 # Enterprise application: ProCoSys - Invitation for Punch-out Api - Dev
        Application__UseAzureAppConfiguration: 'true'
        ApplicationInsights__ConnectionString: InstrumentationKey=298df54f-eae4-4bee-a645-678c3b594883;IngestionEndpoint=https://northeurope-3.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=acf2701d-97da-47c4-bab0-c6ce626e5c97
        ASPNETCORE_ENVIRONMENT: 'Development'
        AzureAd__ClientCredentials__0__SourceType: SignedAssertionFilePath
        AzureAd__ClientId: 2e1868db-3024-45a9-b3f1-568e85586244 # App registration: ProCoSys - Invitation for Punch-out Api - Dev
        AzureAd__MainApiScope: api://dd38f169-bccf-4d0e-a4ad-d830893cfa75/.default
        ConnectionStrings__IPOContext: Server=pcs-dev-sqlserver.database.windows.net;Authentication=Active Directory Workload Identity;Encrypt=True;Database=pcs-ipo-dev-db
        Email__Enabled: true
        Email__EnableSsl: true
        Email__FakeEmail: false
        Email__Server: mrrr.statoil.com
        Graph__ClientId: 0ae66748-e5b8-418b-8f4f-291c368312df # App registration: ProCoSys - Mail
        LEADERELECTOR_SERVICE: http://leader-elector:3003
        Meetings__Environment: ci
        Meetings__PcsBaseUrl: https://dev.pcs-dev.net/
      monitoring: false
      resources:
        requests:
          memory: '1024Mi'
          cpu: '100m'
        limits:
          memory: '1024Mi'
          cpu: '250m'
    # Test environment
    - environment: test
      identity:
        azure:
          clientId: 11325fb8-4b0f-4a20-8d25-9251b8fd8990 # Managed identity: pcs-ipo-test-mi
      variables:
        API__Audience: api://b2b8b455-f2c5-4db9-bce5-62202e64fb31
        Application__AppConfigurationUrl: https://pcs-ipo-non-prod-config.azconfig.io
        Application__LibraryApiScope: api://2df224e7-32fc-4dd8-83b8-d0222327b558/ReadWrite
        Application__ObjectId: 92c17717-142a-4d59-9fea-dfd88b8747ec # Enterprise application: ProCoSys - Invitation for Punch-out Api - Test
        Application__UseAzureAppConfiguration: 'true'
        ApplicationInsights__ConnectionString: InstrumentationKey=ddae94dd-503b-49a6-a54c-e9ece95e4ba4;IngestionEndpoint=https://northeurope-3.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=5a16040d-6c1f-4b45-9312-0be4caf68fb9
        ASPNETCORE_ENVIRONMENT: 'Test'
        AzureAd__ClientCredentials__0__SourceType: SignedAssertionFilePath
        AzureAd__ClientId: b2b8b455-f2c5-4db9-bce5-62202e64fb31 # App registration: ProCoSys - Invitation for Punch-out Api - Test
        AzureAd__MainApiScope: api://2d0ed80f-3013-422d-b8bd-2b8ac70b2ce1/.default
        ConnectionStrings__IPOContext: Server=pcs-test-sqlserver.database.windows.net;Authentication=Active Directory Workload Identity;Encrypt=True;Database=pcs-ipo-test-db-tessell
        Email__Enabled: true
        Email__EnableSsl: true
        Email__FakeEmail: false
        Email__Server: mrrr.statoil.com
        Graph__ClientId: 0ae66748-e5b8-418b-8f4f-291c368312df # App registration: ProCoSys - Mail
        LEADERELECTOR_SERVICE: http://leader-elector:3003
        Meetings__Environment: fqa
        Meetings__PcsBaseUrl: https://procosystest.equinor.com/
      monitoring: false
      replicas: 2
      resources:
        requests:
          memory: '1024Mi'
          cpu: '100m'
        limits:
          memory: '1024Mi'
          cpu: '250m'
    # Prod environment
    - environment: prod
      identity:
        azure:
          clientId: 858de06a-eecf-49f1-ab64-de6d2be03613 # Managed identity: pcs-ipo-prod-mi
      variables:
        API__Audience: api://b3399356-b2b6-44d4-a7b6-323eefc8a173
        Application__AppConfigurationUrl: https://pcs-ipo-prod-config.azconfig.io
        Application__LibraryApiScope: api://6263b7e6-155f-411b-9503-c5c841a601e0/ReadWrite
        Application__ObjectId: 11debf4b-b215-4790-9d3c-eaace6c7a27f # Enterprise application: ProCoSys - Invitation for Punch-out Api - Prod
        Application__UseAzureAppConfiguration: 'true'
        ApplicationInsights__ConnectionString: InstrumentationKey=e8b5ce0a-590d-49ea-8001-f693267fb332;IngestionEndpoint=https://northeurope-3.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=422e8eac-3815-40dd-a46a-d0d5379146e0
        ASPNETCORE_ENVIRONMENT: 'Production'
        AzureAd__ClientCredentials__0__SourceType: SignedAssertionFilePath
        AzureAd__ClientId: b3399356-b2b6-44d4-a7b6-323eefc8a173 # App registration: ProCoSys - Invitation for Punch-out Api - Prod
        AzureAd__MainApiScope: api://47641c40-0135-459b-8ab4-459e68dc8d08/.default
        ConnectionStrings__IPOContext: Server=pcs-prod-sqlserver.database.windows.net;Authentication=Active Directory Workload Identity;Encrypt=True;Database=pcs-ipo-prod-db
        Email__Enabled: true
        Email__EnableSsl: true
        Email__FakeEmail: false
        Email__Server: mrrr.statoil.com
        Graph__ClientId: 0ae66748-e5b8-418b-8f4f-291c368312df # App registration: ProCoSys - Mail
        LEADERELECTOR_SERVICE: http://leader-elector:3003
        Meetings__Environment: fprd
        Meetings__PcsBaseUrl: https://procosys.equinor.com/
      monitoring: false
      replicas: 3
      resources:
        requests:
          memory: '2048Mi'
          cpu: '200m'
        limits:
          memory: '8000Mi'
          cpu: '500m'

  #--------------------
  # LeaderElector 
  #--------------------
  - name: leader-elector
    image: procosys.azurecr.io/leader-elector:{imageTagName}
    ports:
    - name: http
      port: 3003
    publicPort: http
    environmentConfig:
    # Development environment
    - environment: dev
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
    # Test environment
    - environment: test
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
    # Prod environment
    - environment: prod
      imageTagName: latest
      variables:
         LEASE_TIME: 5
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
      monitoring: false
  #--------------------------------
  # External docker image registry
  #--------------------------------
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
      email: arbje@equinor.com
