apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-ipo-api-play
spec:
  environments:
  - name: dev
    build:
      from: poc/sb-receiver

  components:
  # ---------
  # Backend
  #---------- 

  - name: backend
    image: procosys.azurecr.io/ipo/api:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    secrets:
    - CONNECTIONSTRINGS__APPCONFIG # TODO remove this once identity authentication is in use
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: 98cb737b-5c00-4ae6-962b-29c562b7ea21 # Managed identity: pcs-ipo-dev-mi
      imageTagName: latest
      variables:
        Application__AppConfigurationUrl: https://pcs-ipo-non-prod-config.azconfig.io
        Application__UseAzureAppConfiguration: 'true'
        ApplicationInsights__ConnectionString: InstrumentationKey=298df54f-eae4-4bee-a645-678c3b594883;IngestionEndpoint=https://northeurope-3.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=acf2701d-97da-47c4-bab0-c6ce626e5c97
        ASPNETCORE_ENVIRONMENT: 'Development'
        LEADERELECTOR_SERVICE: http://leader-elector:3003
      monitoring: true
      resources:
        requests:
          memory: '1024Mi'
          cpu: '100m'
        limits:
          memory: '1024Mi'
          cpu: '250m'

  #--------------------
  # LeaderElector 
  #--------------------
  - name: leader-elector
    image: procosys.azurecr.io/leader-elector:{imageTagName}
    ports:
    - name: http
      port: 3003
    publicPort: http
    environmentConfig:
    # Development environment
    - environment: dev
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'

  #--------------------
  # Service Bus Processor 
  #--------------------
  - name: processor
    src: src
    dockerfileName: Equinor.ProCoSys.IPO.ServiceBusProcessor/Dockerfile

    environmentConfig:
      - environment: dev

    # Workload Identity for the running application:
    identity:
      azure:
        clientId: 98cb737b-5c00-4ae6-962b-29c562b7ea21 # Managed identity: pcs-ipo-dev-mi

    variables:
      ASPNETCORE_ENVIRONMENT: Development
      TopicSubscriptionOptions__SubscriptionName: temp-subscription.servicebus.windows.net

    horizontalScaling:
      maxReplicas: 1
      minReplicas: 0
      triggers:
        - name: azure-sb
          azureServiceBus:
            namespace: sb-pcs-sandbox #.servicebus.windows.net  # FIXME
            topicName: temp-topic
            subscriptionName: temp-subscription

            # Workload Identity for KEDA to access service bus
            authentication:
              identity:
                azure:
                  clientId: 98cb737b-5c00-4ae6-962b-29c562b7ea21 # Managed identity: pcs-ipo-dev-mi

  #--------------------------------
  # External docker image registry
  #--------------------------------
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
      email: arbje@equinor.com
