apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-ipo-api
spec:
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  # ---------
  # Backend
  #---------- 

  - name: backend
    image: procosys.azurecr.io/ipo/api:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: 98cb737b-5c00-4ae6-962b-29c562b7ea21 # Managed identity: pcs-ipo-dev-mi
      imageTagName: latest
      variables:
        Application__AppConfigurationUrl: https://pcs-ipo-non-prod-config.azconfig.io
        Application__UseAzureAppConfiguration: 'true'
        ApplicationInsights__ConnectionString: InstrumentationKey=298df54f-eae4-4bee-a645-678c3b594883;IngestionEndpoint=https://northeurope-3.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=acf2701d-97da-47c4-bab0-c6ce626e5c97
        ASPNETCORE_ENVIRONMENT: 'Development'
        ConnectionStrings__IPOContext: Server=pcs-dev-sqlserver.database.windows.net;Authentication=Active Directory Workload Identity;Encrypt=True;Database=pcs-ipo-dev-db
        LEADERELECTOR_SERVICE: http://leader-elector:3003
      monitoring: true
      resources:
        requests:
          memory: '1024Mi'
          cpu: '100m'
        limits:
          memory: '1024Mi'
          cpu: '250m'
    # Test environment
    - environment: test
      identity:
        azure:
          clientId: 11325fb8-4b0f-4a20-8d25-9251b8fd8990 # Managed identity: pcs-ipo-test-mi
      variables:
        Application__AppConfigurationUrl: https://pcs-ipo-non-prod-config.azconfig.io
        Application__UseAzureAppConfiguration: 'true'
        ApplicationInsights__ConnectionString: InstrumentationKey=ddae94dd-503b-49a6-a54c-e9ece95e4ba4;IngestionEndpoint=https://northeurope-3.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=5a16040d-6c1f-4b45-9312-0be4caf68fb9
        ASPNETCORE_ENVIRONMENT: 'Test'
        ConnectionStrings__IPOContext: Server=pcs-test-sqlserver.database.windows.net;Authentication=Active Directory Workload Identity;Encrypt=True;Database=pcs-ipo-test-db
        LEADERELECTOR_SERVICE: http://leader-elector:3003
      monitoring: true
      replicas: 2
      resources:
        requests:
          memory: '1024Mi'
          cpu: '100m'
        limits:
          memory: '1024Mi'
          cpu: '250m'
    # Prod environment
    - environment: prod
      identity:
        azure:
          clientId: 858de06a-eecf-49f1-ab64-de6d2be03613 # Managed identity: pcs-ipo-prod-mi
      variables:
        Application__AppConfigurationUrl: https://pcs-ipo-prod-config.azconfig.io
        Application__UseAzureAppConfiguration: 'true'
        ApplicationInsights__ConnectionString: InstrumentationKey=e8b5ce0a-590d-49ea-8001-f693267fb332;IngestionEndpoint=https://northeurope-3.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=422e8eac-3815-40dd-a46a-d0d5379146e0
        ASPNETCORE_ENVIRONMENT: 'Production'
        ConnectionStrings__IPOContext: Server=pcs-prod-sqlserver.database.windows.net;Authentication=Active Directory Workload Identity;Encrypt=True;Database=pcs-ipo-prod-db
        LEADERELECTOR_SERVICE: http://leader-elector:3003
      monitoring: false
      replicas: 3
      resources:
        requests:
          memory: '2048Mi'
          cpu: '200m'
        limits:
          memory: '8000Mi'
          cpu: '500m'

  #--------------------
  # LeaderElector 
  #--------------------
  - name: leader-elector
    image: procosys.azurecr.io/leader-elector:{imageTagName}
    ports:
    - name: http
      port: 3003
    publicPort: http
    environmentConfig:
    # Development environment
    - environment: dev
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
    # Test environment
    - environment: test
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
    # Prod environment
    - environment: prod
      imageTagName: latest
      variables:
         LEASE_TIME: 5
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
      monitoring: false
  #--------------------------------
  # External docker image registry
  #--------------------------------
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
      email: arbje@equinor.com
