IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME = 'Temp' AND TABLE_SCHEMA = 'dbo'
)
BEGIN
    CREATE TABLE Temp (
        Id INT PRIMARY KEY
    );
END

INSERT INTO Temp (Id) VALUES (1);
