name: Build and Push Docker Image
description: 'Build and push Docker image to Azure Container Registry with a tag as the change ID. If the image already exists, it will not be rebuilt.'

inputs:
  client-id:
    description: 'Identity client id'
    required: true
  tenant-id:
    description: 'Equinor tenant id'
    required: true
  tag:
    description: 'Docker image tag to check for existence'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Azure Container Registry
      shell: bash
      run: az acr login --name procosys

    - name: Get DevOps Token
      if: env.IMAGE_EXISTS != 'true'
      id: 'get-devops-token'
      uses: ./.github/actions/get-devops-token

    - name: Build and push Docker image
      if: env.IMAGE_EXISTS != 'true'
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Equinor.ProCoSys.IPO.WebApi/Dockerfile
        push: true
        build-args: |
          FEED_ACCESSTOKEN=${{ steps.get-devops-token.outputs.token }}
          AZURE_CLIENT_ID=${{ inputs.client-id }}
          AZURE_TENANT_ID=${{ inputs.tenant-id }}
        tags: |
          procosys.azurecr.io/api/ipo/api:${{ inputs.tag }}
          procosys.azurecr.io/api/ipo/api:latest
