name: Get Devops token
description: 'Login to Azure and obtain a token for DevOps'
inputs:
  client-id:
    description: 'Identity client id'
    required: true
  tenant-id:
    description: 'Equinor tenant id'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        allow-no-subscriptions: true

    - name: Get Access Token
      shell: bash
      env:
        AZURE_DEVOPS_APPLICATION_ID: "499b84ac-1321-427f-aa17-267ca6975798"
      run: |
        TOKEN=$(az account get-access-token --resource=$AZURE_DEVOPS_APPLICATION_ID | jq -r '.accessToken')
        echo "FEED_ACCESSTOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Configure NuGet source
      shell: bash
      run: |
        dotnet nuget add source --name ProCoSysOfficial \
            --username statoildeveloper \
            --password ${{ env.FEED_ACCESSTOKEN }} \
            --store-password-in-clear-text \
            https://statoildeveloper.pkgs.visualstudio.com/_packaging/ProCoSysOfficial/nuget/v3/index.json