name: 🤖🔗 Run Integration Tests

on:
  workflow_dispatch:
  pull_request:

  # TODO remove
  push:
    branches: ["ci/test-pipeline"]

permissions:
  id-token: write
  contents: read

jobs:
  run-test:
    name: Run integration tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}","clientSecret":"${{ secrets.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'

      - name: Get Access Token
        run: |
          echo "Retrieving access token..."
          echo "TOKEN=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 | jq '.accessToken')" >> $GITHUB_ENV

      - name: Configure NuGet source
        run: |
          nuget sources Add `
            -Name "ProCoSysOfficial" `
            -Source "https://statoildeveloper.pkgs.visualstudio.com/_packaging/ProCoSysOfficial/nuget/v3/index.json" `
            -Username "AzureDevOps" `
            -Password ${{ env.TOKEN }} `
            -StorePasswordInClearText

      - name: NuGet restore
        run: |
          nuget restore ./src/Equinor.ProCoSys.IPO.sln -Verbosity quiet

      - name: Run tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/ -c Release
