name: 🤖🦾 Run Tests

on:
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  run-test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          ./src/Equinor.ProCoSys.IPO.Fam.Tests/,
          ./src/tests/Equinor.ProCoSys.IPO.Command.Tests/,
          ./src/tests/Equinor.ProCoSys.IPO.Domain.Tests/,
          ./src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/,
          ./src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/,
          ./src/tests/Equinor.ProCoSys.IPO.Query.Tests/,
          ./src/tests/Equinor.ProCoSys.IPO.Test.Common/,
          ./src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/,
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Configure Nuget
        uses: ./.github/actions/nuget-config
        with:
          client-id: ${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests - ${{ matrix.project }}
        run: |
          dotnet test ${{ matrix.project }} -c Release
