name: 🤖 Run Tests

on:
  workflow_dispatch:
  pull_request:

  # TODO remove
  push:
    branches: ["ci/test-pipeline"]

permissions:
  id-token: write
  contents: read

jobs:
  run-test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          ./src/Equinor.ProCoSys.IPO.Fam.Tests/
          ./src/tests/Equinor.ProCoSys.IPO.Command.Tests/
          ./src/tests/Equinor.ProCoSys.IPO.Domain.Tests/
          ./src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/
          ./src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/
          ./src/tests/Equinor.ProCoSys.IPO.Query.Tests/
          ./src/tests/Equinor.ProCoSys.IPO.Test.Common/
          ./src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/
          #./src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/ # TODO
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}","clientSecret":"${{ secrets.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'

      - name: Get Access Token
        run: |
          echo "Retrieving access token..."
          TOKEN=$(az account get-access-token --resource=https://pkgs.visualstudio.com --query accessToken -o tsv)
          echo "FEED_ACCESSTOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Configure NuGet source
        run: |
          dotnet nuget add source --name ProCoSysOfficial \
              --username statoildeveloper \
              --password ${{ env.FEED_ACCESSTOKEN }} \
              --store-password-in-clear-text \
              https://statoildeveloper.pkgs.visualstudio.com/_packaging/ProCoSysOfficial/nuget/v3/index.json

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests - ${{ matrix.project }}
        run: |
          dotnet test ${{ matrix.project }} -c Release
