name: 🤖 Run Tests

on:
  workflow_dispatch:
  pull_request:

  # TODO remove
  push:
    branches: ["ci/test-pipeline"]

permissions:
  id-token: write
  contents: read

jobs:
  build-test:
    name: Build & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}","clientSecret":"${{ secrets.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'

      - name: Get Access Token
        run: |
          echo "Retrieving access token..."
          TOKEN=$(az account get-access-token --resource=https://pkgs.visualstudio.com --query accessToken -o tsv)
          echo "FEED_ACCESSTOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Configure NuGet source
        run: |
          dotnet nuget add source --name ProCoSysOfficial \
              --username statoildeveloper \
              --password ${{ env.FEED_ACCESSTOKEN }} \
              --store-password-in-clear-text \
              https://statoildeveloper.pkgs.visualstudio.com/_packaging/ProCoSysOfficial/nuget/v3/index.json

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run FAM tests
        run: |
          dotnet test ./src/Equinor.ProCoSys.IPO.Fam.Tests/ -c Release
          
      - name: Run Command tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.Command.Tests/ -c Release
          
      - name: Run Domain tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.Domain.Tests/ -c Release

      - name: Run Infrastructure tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/ -c Release

      - name: Run MainApi tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/ -c Release

      - name: Run Query tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.Query.Tests/ -c Release

      - name: Run Common tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.Test.Common/ -c Release

      - name: Run WebApi tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/ -c Release

      - name: Run WebApi Integration tests
        run: |
          dotnet test ./src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/ -c Release
