name: ✏️ Verify formatting

on:
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  format-check:
    name: Verify formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          'Command',
          'Domain',
          'Fam',
          'Fam.Tests',
          'ForeignApi',
          'Infrastructure',
          'MessageContracts',
          'Query',
          'WebApi',
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Get DevOps Token
        id: 'get-devops-token'
        uses: ./.github/actions/get-devops-token
      
      - name: Configure Nuget
        uses: ./.github/actions/nuget-config
        with:
          access-token: ${{ steps.get-devops-token.outputs.token }}

      - name: Verify ${{ matrix.project }} formatting
        run: |
          dotnet format ./src/Equinor.ProCoSys.IPO.${{ matrix.project }} --verify-no-changes
