name: 🚀🧪 Deploy to test

on:
  workflow_dispatch:
  push:
    branches: main
  # TODO remove debug
  pull_request:
    types: 
      - reopened
      - opened
      - ready_for_review
      - synchronize
    branches: 
      - main

permissions:
  id-token: write
  contents: read

jobs:
  get-client-id:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      client-id: ${{ steps.get-client-id.outputs.client-id }}
    steps:
      - name: Get app registration client ID
        id: get-client-id
        run: |
          echo "client-id=${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}" >> $GITHUB_OUTPUT
  deploy:
    if: github.event.pull_request.draft == false
    needs: get-client-id
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      client-id: ${{needs.get-client-id.outputs.client-id}}
      tenant-id: ${{ vars.AZURE_TENANT_ID }}
      sql-connection-string: ${{ vars.AZURE_SQL_CONNECTION_STRING }}