name: 🚀 Deploy to environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      client-id:
        description: 'Client ID for Azure login'
        required: true
        type: string
      tenant-id:
        description: 'Tenant ID for Azure login'
        required: true
        type: string
      sql-connection-string:
        description: 'SQL connection string for database migrations'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  # TODO remove debug
  debug-inputs:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Debug inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Client ID: ${{ inputs.client-id }}"
          echo "Tenant ID: ${{ inputs.tenant-id }}"
          echo "SQL Connection String: ${{ inputs.sql-connection-string }}"

  build-and-push-image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.client-id }}
          tenant-id: ${{ inputs.tenant-id }}
          allow-no-subscriptions: true

      - name: Get change ID
        id: get-change-id
        uses: ./.github/actions/get-change-id

      - name: 'Build and Push Image'
        uses: ./.github/actions/docker-build-push-if-not-exists
        with:
          client-id: ${{ inputs.client-id }}
          tenant-id: ${{ inputs.tenant-id }}
          tag: ${{ steps.get-change-id.outputs.change-id }}
  
  generate-migration-script:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.client-id }}
          tenant-id:  ${{ inputs.tenant-id }}
          allow-no-subscriptions: true

      - name: Generate migration script
        id: generate-migration-script
        uses: ./.github/actions/generate-migration-script

      - name: Upload EF Migrations script Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: migration-script
          path: ${{ steps.generate-migration-script.outputs.migration-script-path }}

  migrate-database:
    needs: 
      - build-and-push-image
      - generate-migration-script
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.client-id }}
          tenant-id:  ${{ inputs.tenant-id }}
          allow-no-subscriptions: true 
      
      - uses: actions/download-artifact@v4
        with:
          name: migration-script

      # TODO remove debug
      - name: Debug migration script
        run: |
          echo "Connection string: ${{ inputs.sql-connection-string }}"

      - uses: azure/sql-action@v2.3
        with:        
          connection-string: ${{ inputs.sql-connection-string }}
          path: './migration.sql'

  deploy-to-radix:
    needs:
      - build-and-push-image
      - migrate-database
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Get change ID
        id: get-change-id
        uses: ./.github/actions/get-change-id

      - name: Radix CLI setup
        uses: equinor/radix-github-actions@v2
        with:
          azure_client_id: ${{ inputs.client-id }}

      - name: Deploy to Radix
        run: |
          rx create job deploy \
            --application procosys-ipo-api \
            --from-config \
            --environment ${{ inputs.environment }} \
            --component backend \
            --image-tag-name backend=${{ steps.get-change-id.outputs.change-id }} \
            --follow
