name: 🚀🧪 Deploy to test

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      client-id: ${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}
      tenant-id: ${{ vars.AZURE_TENANT_ID }}
      sql-connection-string: ${{ vars.AZURE_SQL_CONNECTION_STRING }}