name: 🚀🧪 Deploy to test

on:
  workflow_dispatch:
  push:
    branches: main
  # TODO remove debug
  pull_request:
    types: 
      - reopened
      - opened
      - ready_for_review
      - synchronize
    branches: 
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
